apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: linuxwebsite-aci
  namespace: default
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: linuxwebsite-aci
    spec:      
      containers:
        - name: linuxwebsite
          image: marrobi/linuxwebsite
          ports:
          - containerPort: 80
          imagePullPolicy: Always  
      nodeName: virtual-kubelet-connector1-linux 