apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: windowswebsite-aci
  namespace: default
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: windowswebsite-aci
    spec:      
      containers:
        - name: windowswebsite-aci
          #image: marcusreg.azurecr.io/windowswebsite
          image: marrobi/windowswebsite
          ports:
          - containerPort: 80
          imagePullPolicy: Always
      nodeName: aci-connector-1
     # imagePullSecrets:
      #- name:  "azure-registry"