FROM microsoft/windowsservercore:latest

SHELL ["powershell","-command"]

ADD Wait-Service.ps1 /Wait-Service.ps1

RUN Add-WindowsFeature Web-Server

SHELL ["powershell","-file"]

CMD c:\Wait-Service.ps1 -ServiceName W3SVC -AllowServiceRestart