FROM microsoft/windowsservercore:latest

SHELL ["powershell"]

ADD Wait-Service.ps1 /Wait-Service.ps1

RUN Add-WindowsFeature Web-Server

CMD c:\Wait-Service.ps1 -ServiceName W3SVC -AllowServiceRestart